import type { Meal } from "@/types/meal-planner"

export const MEAL_DATABASE: Meal[] = [
  // Breakfast meals
  {
    id: "b1",
    name: "Avocado Toast with Eggs",
    description: "Creamy avocado on toasted bread topped with perfectly cooked eggs",
    ingredients: [
      "2 slices whole grain bread",
      "1 ripe avocado",
      "2 eggs",
      "Salt",
      "Pepper",
      "Olive oil",
      "Lemon juice",
    ],
    instructions: [
      "Toast the bread slices until golden brown",
      "Mash the avocado with lemon juice, salt, and pepper",
      "Cook eggs to your preference (fried, poached, or scrambled)",
      "Spread avocado mixture on toast",
      "Top with cooked eggs and season with salt and pepper",
    ],
    prepTime: 10,
    servings: 2,
    calories: 320,
    category: "breakfast",
    dietTags: ["Vegetarian"],
    allergens: ["Gluten", "Eggs"],
  },
  {
    id: "b2",
    name: "Greek Yogurt Parfait",
    description: "Layered Greek yogurt with fresh berries and granola",
    ingredients: ["1 cup Greek yogurt", "1/2 cup mixed berries", "1/4 cup granola", "1 tbsp honey", "Mint leaves"],
    instructions: [
      "Layer half the yogurt in a glass or bowl",
      "Add half the berries and granola",
      "Repeat layers",
      "Drizzle with honey and garnish with mint",
    ],
    prepTime: 5,
    servings: 1,
    calories: 280,
    category: "breakfast",
    dietTags: ["Vegetarian", "Gluten-Free"],
    allergens: ["Dairy"],
  },
  {
    id: "b3",
    name: "Vegan Smoothie Bowl",
    description: "Thick smoothie bowl topped with fresh fruits and nuts",
    ingredients: [
      "1 frozen banana",
      "1/2 cup frozen berries",
      "1/4 cup almond milk",
      "1 tbsp chia seeds",
      "1/4 cup granola",
      "Fresh fruits for topping",
    ],
    instructions: [
      "Blend frozen banana, berries, and almond milk until thick",
      "Pour into a bowl",
      "Top with chia seeds, granola, and fresh fruits",
      "Serve immediately",
    ],
    prepTime: 8,
    servings: 1,
    calories: 350,
    category: "breakfast",
    dietTags: ["Vegan", "Gluten-Free"],
    allergens: [],
  },
  {
    id: "b4",
    name: "Oatmeal with Berries",
    description: "Warm oatmeal topped with fresh berries and nuts",
    ingredients: [
      "1/2 cup rolled oats",
      "1 cup milk",
      "1/4 cup mixed berries",
      "1 tbsp honey",
      "2 tbsp chopped walnuts",
    ],
    instructions: [
      "Cook oats with milk according to package instructions",
      "Stir in honey",
      "Top with berries and walnuts",
      "Serve warm",
    ],
    prepTime: 10,
    servings: 1,
    calories: 300,
    category: "breakfast",
    dietTags: ["Vegetarian"],
    allergens: ["Dairy", "Nuts"],
  },

  // Lunch meals
  {
    id: "l1",
    name: "Mediterranean Quinoa Salad",
    description: "Fresh quinoa salad with vegetables, feta, and herbs",
    ingredients: [
      "1 cup cooked quinoa",
      "1/2 cup cherry tomatoes",
      "1/4 cup cucumber",
      "1/4 cup red onion",
      "1/4 cup feta cheese",
      "2 tbsp olive oil",
      "1 tbsp lemon juice",
      "Fresh herbs",
    ],
    instructions: [
      "Cook quinoa according to package instructions and let cool",
      "Dice tomatoes, cucumber, and red onion",
      "Mix quinoa with vegetables and feta",
      "Whisk olive oil and lemon juice for dressing",
      "Toss salad with dressing and herbs",
    ],
    prepTime: 15,
    servings: 2,
    calories: 380,
    category: "lunch",
    dietTags: ["Vegetarian", "Mediterranean", "Gluten-Free"],
    allergens: ["Dairy"],
  },
  {
    id: "l2",
    name: "Chicken Caesar Wrap",
    description: "Grilled chicken with Caesar dressing in a tortilla wrap",
    ingredients: [
      "1 large tortilla",
      "4 oz grilled chicken breast",
      "2 cups romaine lettuce",
      "2 tbsp Caesar dressing",
      "2 tbsp parmesan cheese",
      "Croutons",
    ],
    instructions: [
      "Grill chicken breast and slice",
      "Chop romaine lettuce",
      "Spread Caesar dressing on tortilla",
      "Add lettuce, chicken, cheese, and croutons",
      "Roll tightly and cut in half",
    ],
    prepTime: 12,
    servings: 1,
    calories: 450,
    category: "lunch",
    dietTags: [],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "l3",
    name: "Vegetable Stir Fry",
    description: "Colorful mixed vegetables stir-fried with ginger and soy sauce",
    ingredients: [
      "2 cups mixed vegetables",
      "2 tbsp vegetable oil",
      "1 tbsp ginger",
      "2 cloves garlic",
      "2 tbsp soy sauce",
      "1 tsp sesame oil",
      "Green onions",
    ],
    instructions: [
      "Heat oil in a wok or large pan",
      "Add ginger and garlic, stir for 30 seconds",
      "Add vegetables and stir-fry for 5-7 minutes",
      "Add soy sauce and sesame oil",
      "Garnish with green onions",
    ],
    prepTime: 15,
    servings: 2,
    calories: 220,
    category: "lunch",
    dietTags: ["Vegan", "Vegetarian"],
    allergens: ["Soy"],
  },
  {
    id: "l4",
    name: "Turkey and Avocado Sandwich",
    description: "Fresh turkey sandwich with avocado and vegetables",
    ingredients: [
      "2 slices whole grain bread",
      "4 oz sliced turkey",
      "1/2 avocado",
      "2 lettuce leaves",
      "2 tomato slices",
      "1 tbsp mayo",
      "Salt and pepper",
    ],
    instructions: [
      "Toast bread if desired",
      "Spread mayo on one slice",
      "Layer turkey, avocado, lettuce, and tomato",
      "Season with salt and pepper",
      "Top with second slice and cut diagonally",
    ],
    prepTime: 8,
    servings: 1,
    calories: 420,
    category: "lunch",
    dietTags: [],
    allergens: ["Gluten"],
  },

  // Dinner meals
  {
    id: "d1",
    name: "Grilled Salmon with Vegetables",
    description: "Perfectly grilled salmon with roasted seasonal vegetables",
    ingredients: [
      "6 oz salmon fillet",
      "2 cups mixed vegetables",
      "2 tbsp olive oil",
      "1 lemon",
      "Salt",
      "Pepper",
      "Fresh herbs",
    ],
    instructions: [
      "Preheat grill to medium-high heat",
      "Season salmon with salt, pepper, and lemon",
      "Toss vegetables with olive oil and seasonings",
      "Grill salmon for 4-5 minutes per side",
      "Roast vegetables at 400°F for 20 minutes",
      "Serve with lemon wedges and herbs",
    ],
    prepTime: 25,
    servings: 2,
    calories: 480,
    category: "dinner",
    dietTags: ["Gluten-Free", "Keto", "Paleo"],
    allergens: ["Fish"],
  },
  {
    id: "d2",
    name: "Vegetarian Pasta Primavera",
    description: "Fresh pasta with seasonal vegetables in a light sauce",
    ingredients: [
      "8 oz pasta",
      "2 cups mixed vegetables",
      "3 cloves garlic",
      "1/4 cup olive oil",
      "1/2 cup parmesan cheese",
      "Fresh basil",
      "Salt and pepper",
    ],
    instructions: [
      "Cook pasta according to package directions",
      "Sauté vegetables and garlic in olive oil",
      "Drain pasta and reserve 1/2 cup pasta water",
      "Toss pasta with vegetables and cheese",
      "Add pasta water if needed for consistency",
      "Garnish with fresh basil",
    ],
    prepTime: 20,
    servings: 4,
    calories: 380,
    category: "dinner",
    dietTags: ["Vegetarian"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "d3",
    name: "Chicken Stir Fry with Rice",
    description: "Tender chicken with vegetables served over steamed rice",
    ingredients: [
      "6 oz chicken breast",
      "2 cups mixed vegetables",
      "1 cup cooked rice",
      "2 tbsp soy sauce",
      "1 tbsp vegetable oil",
      "1 tsp ginger",
      "2 cloves garlic",
    ],
    instructions: [
      "Cut chicken into bite-sized pieces",
      "Heat oil in a wok or large pan",
      "Cook chicken until golden, remove and set aside",
      "Stir-fry vegetables with ginger and garlic",
      "Return chicken to pan, add soy sauce",
      "Serve over steamed rice",
    ],
    prepTime: 18,
    servings: 2,
    calories: 520,
    category: "dinner",
    dietTags: [],
    allergens: ["Soy"],
  },
  {
    id: "d4",
    name: "Lentil Curry",
    description: "Hearty lentil curry with aromatic spices",
    ingredients: [
      "1 cup red lentils",
      "1 can coconut milk",
      "1 onion",
      "3 cloves garlic",
      "1 tbsp curry powder",
      "1 tsp turmeric",
      "2 cups vegetable broth",
      "Cilantro",
    ],
    instructions: [
      "Sauté diced onion and garlic until soft",
      "Add curry powder and turmeric, cook for 1 minute",
      "Add lentils, coconut milk, and broth",
      "Simmer for 20-25 minutes until lentils are tender",
      "Season with salt and pepper",
      "Garnish with fresh cilantro",
    ],
    prepTime: 30,
    servings: 4,
    calories: 320,
    category: "dinner",
    dietTags: ["Vegan", "Vegetarian", "Gluten-Free"],
    allergens: [],
  },
]
